# Use `conda env create slot-tracker-environment.yml` to create the environment
name: slot-tracker
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - notebook
  - pylint
  - black
  - pytesseract
  - pillow
  - pyautogui
  - opencv
  - imutils
  - matplotlib
  - time
  - pandas
  # - pip:
  #     - xgboost
